### ISSUE TITLE
doesent work with Textarea

### ISSUE THREAD

**Issue by devlau** [anein/angular2-trim-directive#8]
Hello Sir,

great directive!
I had just one small request if possible.
Your directive does not work with <textarea> out of the box.
The fix seems pretty simple.
I changed line 39 in input-trim.directive.js from:

`selector: 'input[trim] ',`

to:

`selector: 'input[trim] , textarea[trim]',`

Which seems to fix the problem.
However I am a bit of a novice at this, and would love for it to work out of the box as I seem to have a bit of a problem saving those changes.
Thanks for the great directive, keep up the good work 👍

**Comment by anein** [comment]
Greetings.

Yes, the directive doesn't work with the textarea field because, out of the box, it doesn't allow you to add new lines, and therefore such behavior violates the whole concept of textarea. The directive will trim value of <textarea> properly if the "blur" event is set as the attribute's value. Thus, I think, the best choice is to use "textarea[trim="blur"]" as a selector. 

Anyway, if you wish, I can add "textarea[trim]" or you can create a PR. 😇

And I apologize for taking so long in responding to your request.
